### ISSUE TITLE
html/js table çalışması

### ISSUE THREAD

**Issue by gamzecanli** [gamzecanli/js#1]
Aşagıdaki html de çalışacak ve ekrandan girilen satır,sutun ve içerik degerini alacak javascript fonksiyonu yaz. Degerler alındıktan sonra girilen satır ve sutundaki yere içerik yazılmalı.

```
<!DOCTYPE html>  
<html><head><br><meta charset=utf-8 />  
<title>Change the content of a cell</title>  
</head><body>  
<table id="myTable" border="1">  
<tr><td>Row1 cell1</td>  
<td>Row1 cell2</td></tr>  
<tr><td>Row2 cell1</td>  
<td>Row2 cell2</td></tr>  
<tr><td>Row3 cell1</td>  
<td>Row3 cell2</td></tr>  
</table><form>  
<input type="button" onclick="changeContent()" value="Change content">  
</form></body></html>  

```

**Comment by gamzecanli** [comment]
- Satır ve sütun değerlerinde bir kısıtlama var mıdır?
- Aynı satır ve sutuna tekrar değer girilmeye çalışılırsa ne olması beklenir?

@hilaltanriverdi

**Comment by hilaltanriverdi** [comment]
-Verilen tablonun satır ve sutun sayısında degişiklik yapılmayacak. 
-Aynı satır ve sutuna tekrar deger girilmeye çalışıldıgında var olan degerin güncellenmesi beklenmektedir
